// default-schema.js
// Seeds data/schema.json on first boot. After that, the schema lives
// entirely in data/schema.json and is edited through /admin.

module.exports = {
  navOrder: ['landlords', 'tenants', 'banking', 'property', 'bills', 'payees', 'payments'],

  entities: {

    landlords: {
      key: 'landlords',
      label: 'Landlords',
      singular: 'Landlord',
      pk: 'LL_Code',
      displayField: 'LL_Display',
      displayPrefix: '',
      listTitle: '',
      detailTitle: '',
      auditEnabled: false,
      fields: [
        { name: 'LL_Code', label: 'Landlord Code', type: 'text', required: true, key: true, inList: true },
        { name: 'LL_Display', label: 'Display Name', type: 'text', inList: true },
        { name: 'LL_PAN', label: 'PAN', type: 'text', inList: true },
        { name: 'LL_GSTIN', label: 'GSTIN', type: 'text', inList: false },
        { name: 'LL_GSTIN_Uname', label: 'GSTIN Username', type: 'text', inList: false },
        { name: 'LL_Address', label: 'Address', type: 'textarea', inList: false },
        { name: 'LL_Phone', label: 'Phone', type: 'text', inList: true },
        { name: 'LL_email', label: 'Email', type: 'text', inList: true },
        { name: 'LL_Invoice_Type', label: 'Invoice Type', type: 'text', inList: true },
        { name: 'LL_BillAddr', label: 'Billing Address', type: 'textarea', inList: false },
      ],
    },

    tenants: {
      key: 'tenants',
      label: 'Tenants',
      singular: 'Tenant',
      pk: 'T_Client_Code',
      displayField: 'T_Client_Short_Name',
      displayPrefix: '',
      listTitle: '',
      detailTitle: '',
      auditEnabled: false,
      fields: [
        { name: 'T_Client_Code', label: 'Client Code', type: 'text', required: true, key: true, inList: true },
        { name: 'T_Client_Short_Name', label: 'Short Name', type: 'text', inList: true },
        { name: 'T_MappedTo', label: 'Landlord', type: 'fk', ref: 'landlords', inList: true },
        { name: 'T_Client_Name', label: 'Client Name', type: 'text', inList: true },
        { name: 'T_Billing_Address', label: 'Billing Address', type: 'textarea', inList: false },
        { name: 'T_Client_PAN', label: 'Client PAN', type: 'text', inList: false },
        { name: 'T_Client_GSTN', label: 'Client GSTN', type: 'text', inList: false },
        { name: 'T_Invoice_Value', label: 'Invoice Value', type: 'number', inList: false },
        { name: 'T_Client_Short_Name2', label: 'Short Name 2', type: 'text', inList: false },
        { name: 'T_Bill_Description_1', label: 'Bill Description 1', type: 'textarea', inList: false },
        { name: 'T_Bill_Description_2', label: 'Bill Description 2', type: 'textarea', inList: false },
        { name: 'T_SAC', label: 'SAC', type: 'text', inList: false },
        { name: 'T_Deposit_Account', label: 'Deposit Account', type: 'fk', ref: 'banking', inList: false },
        { name: 'T_Additional_Info', label: 'Additional Info', type: 'textarea', inList: false },
        { name: 'T_AdvanceHeld', label: 'Advance Held', type: 'number', inList: false },
        { name: 'T_Start', label: 'Start Date', type: 'date', inList: false },
        { name: 'T_Expiry', label: 'Expiry Date', type: 'date', inList: true },
        { name: 'T_Monthly_Deposit_Deduction', label: 'Monthly Deposit Deduction', type: 'number', inList: false },
        { name: 'T_Property_Code', label: 'Property', type: 'fk', ref: 'property', inList: true },
        { name: 'T_Share', label: 'Share', type: 'number', inList: false },
        { name: 'T_TDS_Debitor', label: 'TDS Debitor', type: 'bool', inList: false },
        { name: 'T_Advance_Received_Date', label: 'Advance Received Date', type: 'number', inList: false },
        { name: 'T_Advance_Return_Date', label: 'Advance Return Date', type: 'number', inList: false },
        { name: 'T_Notes', label: 'Notes', type: 'textarea', inList: false },
        { name: 'T_Active', label: 'Active', type: 'bool', inList: true },
        { name: 'T_InvoiceType', label: 'Invoice Type', type: 'text', inList: false },
      ],
    },

    banking: {
      key: 'banking',
      label: 'Banking',
      singular: 'Bank Account',
      pk: 'BANK_CODE',
      displayField: 'BANK_Details_Short',
      displayPrefix: '',
      listTitle: '',
      detailTitle: '',
      auditEnabled: false,
      fields: [
        { name: 'BANK_CODE', label: 'Bank Code', type: 'text', required: true, key: true, inList: true },
        { name: 'BANK_Desc', label: 'Description', type: 'text', inList: true },
        { name: 'BANK_MappedTo', label: 'Landlord', type: 'fk', ref: 'landlords', inList: true },
        { name: 'BANK_Details', label: 'Details', type: 'text', inList: false },
        { name: 'BANK_Details_Short', label: 'Details (Short)', type: 'text', inList: false },
        { name: 'BANK_Account', label: 'Account Number', type: 'text', inList: true },
        { name: 'BANK_Account_Type', label: 'Account Type', type: 'text', inList: true },
        { name: 'BANK_Status', label: 'Status', type: 'text', inList: true },
        { name: 'BANK_Nominee', label: 'Nominee', type: 'text', inList: false },
        { name: 'BANK_Open_Date', label: 'Open Date', type: 'date', inList: false },
        { name: 'BANK_Close_Date', label: 'Close Date', type: 'date', inList: false },
        { name: 'BANK_CustID', label: 'Customer ID', type: 'text', inList: false },
        { name: 'BANK_Misc_1', label: 'Misc 1', type: 'text', inList: false },
        { name: 'BANK_MB', label: 'Mobile Banking', type: 'text', inList: false },
        { name: 'BANK_DC', label: 'Debit Card', type: 'text', inList: false },
        { name: 'BANK_CCLim', label: 'Credit Card Limit', type: 'number', inList: false },
        { name: 'BANK_CC_Charges', label: 'CC Charges', type: 'number', inList: false },
        { name: 'BANK_CC_Fee_Waiver', label: 'CC Fee Waiver', type: 'number', inList: false },
        { name: 'BANK_CC_SECU', label: 'CC Secured', type: 'text', inList: false },
        { name: 'BANK_CC_SECDEP', label: 'CC Security Deposit', type: 'number', inList: false },
        { name: 'BANK_CustCare', label: 'Customer Care', type: 'textarea', inList: false },
        { name: 'BANK_Notes', label: 'Notes', type: 'textarea', inList: false },
      ],
    },

    property: {
      key: 'property',
      label: 'Property',
      singular: 'Property',
      pk: 'PROP_CODE',
      displayField: 'PROP_PropShortName',
      displayPrefix: '',
      listTitle: '',
      detailTitle: '',
      auditEnabled: false,
      fields: [
        { name: 'PROP_CODE', label: 'Property Code', type: 'text', required: true, key: true, inList: true },
        { name: 'PROP_PropShortName', label: 'Short Name', type: 'text', inList: true },
        { name: 'PROP_Landlord', label: 'Landlord', type: 'fk', ref: 'landlords', inList: true },
        { name: 'PROP_PID', label: 'PID', type: 'text', inList: false },
        { name: 'PROP_PID_New', label: 'PID (New)', type: 'text', inList: false },
        { name: 'PROP_Prop_No', label: 'Property No.', type: 'text', inList: false },
        { name: 'PROP_Owner_Name', label: 'Owner Name', type: 'text', inList: true },
        { name: 'PROP_Property_Address', label: 'Property Address', type: 'textarea', inList: false },
        { name: 'PROP_Prop_Long_Name', label: 'Property Long Name', type: 'textarea', inList: false },
        { name: 'PROP_Postal_Code', label: 'Postal Code', type: 'number', inList: true },
        { name: 'PROP_App_No_0809', label: 'Application No. 08-09', type: 'text', inList: false },
        { name: 'PROP_App_No_1516', label: 'Application No. 15-16', type: 'text', inList: false },
        { name: 'PROP_App_No_1617', label: 'Application No. 16-17', type: 'text', inList: false },
        { name: 'PROP_Old_Zone', label: 'Old Zone', type: 'text', inList: false },
        { name: 'PROP_New_Zone', label: 'New Zone', type: 'text', inList: false },
        { name: 'PROP_Capped_Zone', label: 'Capped Zone', type: 'text', inList: false },
        { name: 'PROP_Site_Area_SFT', label: 'Site Area (SFT)', type: 'number', inList: false },
        { name: 'PROP_BUA_SFT', label: 'BUA (SFT)', type: 'number', inList: true },
        { name: 'PROP_Cost_Price', label: 'Cost Price', type: 'number', inList: false },
      ],
    },

    billseries: {
      key: 'billseries',
      label: 'Bill Series',
      singular: 'Bill Series',
      pk: 'BS_ID',
      displayField: '',
      displayPrefix: 'Series #',
      listTitle: '',
      detailTitle: '',
      auditEnabled: false,
      fields: [
        { name: 'BS_ID', label: 'ID', type: 'number', required: true, key: true, auto: true, inList: true },
        { name: 'BS_Landlord', label: 'Landlord', type: 'fk', ref: 'landlords', inList: true },
        { name: 'BS_LastNumber', label: 'Last Bill Number Issued', type: 'number', inList: true },
      ],
    },

    bills: {
      key: 'bills',
      label: 'Bills',
      singular: 'Bill',
      pk: 'BILLS_BillNum',
      displayField: '',
      displayPrefix: 'Bill #',
      listTitle: '',
      detailTitle: '',
      auditEnabled: false,
      fields: [
        { name: 'BILLS_BillNum', label: 'Bill No. (internal)', type: 'number', required: true, key: true, auto: true, inList: false },
        { name: 'BILLS_SeriesNo', label: 'Bill No. (Landlord Series)', type: 'series', inList: true,
          seriesGroupPath: 'BILLS_ClientCode.T_MappedTo', seriesTrackerEntity: 'billseries',
          seriesTrackerGroupField: 'BS_Landlord', seriesTrackerCounterField: 'BS_LastNumber' },
        { name: 'BILLS_ClientCode', label: 'Tenant', type: 'fk', ref: 'tenants', inList: true },
        { name: 'BILLS_BillDate', label: 'Bill Date', type: 'date', inList: true },
        { name: 'BILLS_BillGenDate', label: 'Bill Gen. Timestamp', type: 'timestamp', inList: false },
        { name: 'BILLS_Description', label: 'Description', type: 'textarea', inList: false },
        { name: 'BILLS_Total', label: 'Total', type: 'number', inList: true },
        { name: 'BILLS_RentRecd', label: 'Rent Received', type: 'number', inList: true },
        { name: 'BILLS_RentRecdDate', label: 'Rent Received Date', type: 'date', inList: false },
        { name: 'BILLS_TDSDep', label: 'TDS Deposited', type: 'number', inList: false },
        { name: 'BILLS_TDSDepDate', label: 'TDS Deposited Date', type: 'date', inList: false },
        { name: 'BILLS_GSTRecd', label: 'GST Received', type: 'number', inList: false },
        { name: 'BILLS_GSTRecdDate', label: 'GST Received Date', type: 'date', inList: false },
        { name: 'BILLS_Mode', label: 'Mode', type: 'text', inList: true },
        { name: 'BILLS_Ref', label: 'Reference', type: 'text', inList: false },
        { name: 'BILLS_GSTR1Check', label: 'GSTR-1 Checked', type: 'bool', inList: true },
        { name: 'BILLS_GSTR1FiledOn', label: 'GSTR-1 Filed On', type: 'date', inList: false },
        { name: 'BILLS_GSTR1Ref', label: 'GSTR-1 Reference', type: 'text', inList: false },
        { name: 'BILLS_GSTR1Issue', label: 'GSTR-1 Issue', type: 'textarea', inList: false },
        { name: 'BILLS_GSTR1Resolution', label: 'GSTR-1 Resolution', type: 'textarea', inList: false },
        { name: 'BILLS_GSTR3BPaid', label: 'GSTR-3B Paid', type: 'number', inList: false },
        { name: 'BILLS_GSTR3BPaidOn', label: 'GSTR-3B Paid On', type: 'date', inList: false },
        { name: 'BILLS_GSTR3BRef', label: 'GSTR-3B Reference', type: 'text', inList: false },
        { name: 'BILLS_GSTTDSRecd', label: 'GST TDS Received', type: 'number', inList: false },
        { name: 'BILLS_TDSCreditFiledOn', label: 'TDS Credit Filed On', type: 'date', inList: false },
        { name: 'BILLS_TDSClaimRef', label: 'TDS Claim Reference', type: 'text', inList: false },
        { name: 'BILLS_Comments', label: 'Comments', type: 'textarea', inList: false },
      ],
    },

    payees: {
      key: 'payees',
      label: 'Payees',
      singular: 'Payee',
      pk: 'PAY_Name',
      displayField: 'PAY_Name',
      displayPrefix: '',
      listTitle: 'Vendor & Salary Payees',
      detailTitle: '',
      auditEnabled: false,
      fields: [
        { name: 'PAY_Name', label: 'Payee Name', type: 'text', required: true, key: true, inList: true },
        { name: 'PAY_Method', label: 'Payment Method', type: 'picklist', picklistSource: 'custom', picklistValues: [{ key: 'upi-id', label: 'UPI ID', active: true }, { key: 'bank-account', label: 'Bank Account', active: true }], required: true, inList: true },
        { name: 'PAY_UPI_ID', label: 'UPI ID', type: 'text', inList: true },
        { name: 'PAY_AccountNum', label: 'Account Number', type: 'text', inList: false },
        { name: 'PAY_IFSC', label: 'IFSC', type: 'text', inList: false },
        // Narration template can reference {{PREV_MONTH}} — resolved when a new payment
        // record is being created, then stored as text on the payment. Example:
        //   "Ambika Salary - {{PREV_MONTH}}"  ->  "Ambika Salary - Jun 2026"
        { name: 'PAY_NarrationTemplate', label: 'Narration Template', type: 'text', inList: false },
        // Last-paid amount and date come from a LATEST rollup on payments, so the
        // payee's detail page immediately shows "when did I last pay them, and how much".
        { name: 'PAY_LastPaidAmount', label: 'Last Paid Amount', type: 'rollup', format: 'currency', inList: true,
          rollupFn: 'LATEST', rollupHop1Entity: 'payments',
          rollupField: 'PMT_Amount', rollupOrderField: 'PMT_Date' },
        { name: 'PAY_LastPaidDate', label: 'Last Paid Date', type: 'rollup', format: 'date', inList: true,
          rollupFn: 'LATEST', rollupHop1Entity: 'payments',
          rollupField: 'PMT_Date', rollupOrderField: 'PMT_Date' },
      ],
    },

    payments: {
      key: 'payments',
      label: 'Payments',
      singular: 'Payment',
      pk: 'PMT_ID',
      displayField: '',
      displayPrefix: 'PMT-',
      listTitle: 'UPI Payment History',
      detailTitle: '',
      auditEnabled: false,
      fields: [
        { name: 'PMT_ID', label: 'Payment ID', type: 'number', required: true, key: true, auto: true, inList: true },
        { name: 'PMT_Date', label: 'Date', type: 'date', required: true, inList: true },
        { name: 'PMT_Payee', label: 'Payee', type: 'fk', ref: 'payees', required: true, inList: true },
        { name: 'PMT_Amount', label: 'Amount', type: 'currency', required: true, inList: true },
        { name: 'PMT_Notes', label: 'Notes', type: 'textarea', rows: 2, inList: true },
        // Month formula for grouping/filtering later — same formatting as the Excel version.
        { name: 'PMT_Month', label: 'Month', type: 'formula', format: 'plain', inList: false,
          formula: 'CONCAT(YEAR(PMT_Date), "-", MONTH(PMT_Date))' },
      ],
    },

  },
};
