// seed.js — sample starter data, written to data/db.json on first boot.
module.exports = {
  landlords: [
    {
      LL_Code: 'LL-001',
      LL_Display: 'Muneesh Family Trust',
      LL_PAN: 'AAAPM1234A',
      LL_GSTIN: '29AAAPM1234A1Z5',
      LL_GSTIN_Uname: 'muneeshtrust',
      LL_Address: '12 Lavelle Road, Bengaluru, KA 560001',
      LL_Phone: '+91 98450 11223',
      LL_email: 'accounts@muneeshtrust.example',
      LL_Invoice_Type: 'GST Invoice',
      LL_BillAddr: '12 Lavelle Road, Bengaluru, KA 560001',
    },
    {
      LL_Code: 'LL-002',
      LL_Display: 'Legacy Holdings LLP',
      LL_PAN: 'AAFPL5678B',
      LL_GSTIN: '29AAFPL5678B1Z2',
      LL_GSTIN_Uname: 'legacyholdings',
      LL_Address: '45 MG Road, Bengaluru, KA 560025',
      LL_Phone: '+91 98860 44556',
      LL_email: 'finance@legacyholdings.example',
      LL_Invoice_Type: 'Non-GST',
      LL_BillAddr: '45 MG Road, Bengaluru, KA 560025',
    },
  ],

  banking: [
    {
      BANK_CODE: 'BNK-001',
      BANK_Desc: 'HDFC Current Account - Trust',
      BANK_MappedTo: 'LL-001',
      BANK_Details: 'HDFC Bank, Lavelle Road Branch',
      BANK_Details_Short: 'HDFC-LR',
      BANK_Account: 'XXXXXXXX4521',
      BANK_Account_Type: 'Current',
      BANK_Status: 'Active',
      BANK_Nominee: 'R. Muneesh',
      BANK_Open_Date: '2015-04-01',
      BANK_Close_Date: '',
      BANK_CustID: 'CUST88213',
      BANK_Misc_1: '',
      BANK_MB: 'Enabled',
      BANK_DC: 'Enabled',
      BANK_CCLim: 0,
      BANK_CC_Charges: 0,
      BANK_CC_Fee_Waiver: 0,
      BANK_CC_SECU: '',
      BANK_CC_SECDEP: 0,
      BANK_CustCare: '1800-202-6161',
      BANK_Notes: 'Primary rent collection account.',
    },
    {
      BANK_CODE: 'BNK-002',
      BANK_Desc: 'ICICI Savings - Legacy Holdings',
      BANK_MappedTo: 'LL-002',
      BANK_Details: 'ICICI Bank, MG Road Branch',
      BANK_Details_Short: 'ICICI-MG',
      BANK_Account: 'XXXXXXXX9987',
      BANK_Account_Type: 'Savings',
      BANK_Status: 'Active',
      BANK_Nominee: 'S. Rao',
      BANK_Open_Date: '2018-07-12',
      BANK_Close_Date: '',
      BANK_CustID: 'CUST44120',
      BANK_Misc_1: '',
      BANK_MB: 'Enabled',
      BANK_DC: 'Disabled',
      BANK_CCLim: 0,
      BANK_CC_Charges: 0,
      BANK_CC_Fee_Waiver: 0,
      BANK_CC_SECU: '',
      BANK_CC_SECDEP: 0,
      BANK_CustCare: '1800-1080',
      BANK_Notes: 'Used for security deposits.',
    },
  ],

  property: [
    {
      PROP_CODE: 'PROP-001',
      PROP_PropShortName: 'Lavelle Arcade',
      PROP_Landlord: 'LL-001',
      PROP_PID: 'PID-77-A',
      PROP_PID_New: 'PID-N-77-A',
      PROP_Prop_No: '12',
      PROP_Owner_Name: 'Muneesh Family Trust',
      PROP_Property_Address: '12 Lavelle Road, Bengaluru, KA 560001',
      PROP_Prop_Long_Name: 'Lavelle Arcade Commercial Complex',
      PROP_Postal_Code: 560001,
      PROP_App_No_0809: 'A0809-231',
      PROP_App_No_1516: 'A1516-987',
      PROP_App_No_1617: 'A1617-102',
      PROP_Old_Zone: 'C',
      PROP_New_Zone: 'B',
      PROP_Capped_Zone: 'B',
      PROP_Site_Area_SFT: 8500,
      PROP_BUA_SFT: 21000,
      PROP_Cost_Price: 185000000,
    },
    {
      PROP_CODE: 'PROP-002',
      PROP_PropShortName: 'MG Business Center',
      PROP_Landlord: 'LL-002',
      PROP_PID: 'PID-14-B',
      PROP_PID_New: 'PID-N-14-B',
      PROP_Prop_No: '45',
      PROP_Owner_Name: 'Legacy Holdings LLP',
      PROP_Property_Address: '45 MG Road, Bengaluru, KA 560025',
      PROP_Prop_Long_Name: 'MG Road Business Center Tower',
      PROP_Postal_Code: 560025,
      PROP_App_No_0809: 'A0809-556',
      PROP_App_No_1516: 'A1516-778',
      PROP_App_No_1617: 'A1617-330',
      PROP_Old_Zone: 'A',
      PROP_New_Zone: 'A',
      PROP_Capped_Zone: 'A',
      PROP_Site_Area_SFT: 6200,
      PROP_BUA_SFT: 15400,
      PROP_Cost_Price: 142000000,
    },
  ],

  tenants: [
    {
      T_Client_Code: 'TEN-001',
      T_Client_Short_Name: 'BrightTech',
      T_MappedTo: 'LL-001',
      T_Client_Name: 'BrightTech Solutions Pvt Ltd',
      T_Billing_Address: '3rd Floor, Lavelle Arcade, Bengaluru',
      T_Client_PAN: 'AACCB4321C',
      T_Client_GSTN: '29AACCB4321C1ZP',
      T_Invoice_Value: 385000,
      T_Client_Short_Name2: 'BTS',
      T_Bill_Description_1: 'Office rent - 3rd Floor',
      T_Bill_Description_2: 'CAM charges',
      T_SAC: '997212',
      T_Deposit_Account: 'BNK-001',
      T_Additional_Info: 'Lease renewed FY25-26',
      T_AdvanceHeld: 1155000,
      T_Start: '2023-06-01',
      T_Expiry: '2028-05-31',
      T_Monthly_Deposit_Deduction: 0,
      T_Property_Code: 'PROP-001',
      T_Share: 100,
      T_TDS_Debitor: true,
      T_Advance_Received_Date: 20230601,
      T_Advance_Return_Date: 0,
      T_Notes: 'Preferred tenant, always pays by 5th.',
      T_Active: true,
      T_InvoiceType: 'GST Invoice',
    },
    {
      T_Client_Code: 'TEN-002',
      T_Client_Short_Name: 'Café Aroma',
      T_MappedTo: 'LL-001',
      T_Client_Name: 'Aroma Foods & Beverages',
      T_Billing_Address: 'Ground Floor, Lavelle Arcade, Bengaluru',
      T_Client_PAN: 'AAECA7788D',
      T_Client_GSTN: '29AAECA7788D1ZQ',
      T_Invoice_Value: 165000,
      T_Client_Short_Name2: 'Aroma',
      T_Bill_Description_1: 'Retail rent - Ground Floor Unit 3',
      T_Bill_Description_2: '',
      T_SAC: '997212',
      T_Deposit_Account: 'BNK-001',
      T_Additional_Info: '',
      T_AdvanceHeld: 495000,
      T_Start: '2022-01-15',
      T_Expiry: '2027-01-14',
      T_Monthly_Deposit_Deduction: 0,
      T_Property_Code: 'PROP-001',
      T_Share: 100,
      T_TDS_Debitor: true,
      T_Advance_Received_Date: 20220115,
      T_Advance_Return_Date: 0,
      T_Notes: '',
      T_Active: true,
      T_InvoiceType: 'GST Invoice',
    },
    {
      T_Client_Code: 'TEN-003',
      T_Client_Short_Name: 'Vertex Legal',
      T_MappedTo: 'LL-002',
      T_Client_Name: 'Vertex Legal Associates',
      T_Billing_Address: '5th Floor, MG Business Center, Bengaluru',
      T_Client_PAN: 'AAJFV9012E',
      T_Client_GSTN: '29AAJFV9012E1ZR',
      T_Invoice_Value: 275000,
      T_Client_Short_Name2: 'Vertex',
      T_Bill_Description_1: 'Office rent - 5th Floor',
      T_Bill_Description_2: 'Parking charges',
      T_SAC: '997212',
      T_Deposit_Account: 'BNK-002',
      T_Additional_Info: '',
      T_AdvanceHeld: 825000,
      T_Start: '2024-03-01',
      T_Expiry: '2029-02-28',
      T_Monthly_Deposit_Deduction: 0,
      T_Property_Code: 'PROP-002',
      T_Share: 100,
      T_TDS_Debitor: false,
      T_Advance_Received_Date: 20240301,
      T_Advance_Return_Date: 0,
      T_Notes: 'Law firm, invoices need extra detail.',
      T_Active: true,
      T_InvoiceType: 'Non-GST',
    },
  ],

  bills: [
    {
      BILLS_BillNum: 1,
      BILLS_ClientCode: 'TEN-001',
      BILLS_BillDate: '2026-06-01',
      BILLS_BillGenDate: '2026-06-01T09:12:00',
      BILLS_Description: 'Rent for June 2026',
      BILLS_Total: 385000,
      BILLS_RentRecd: 385000,
      BILLS_RentRecdDate: '2026-06-04',
      BILLS_TDSDep: 38500,
      BILLS_TDSDepDate: '2026-06-07',
      BILLS_GSTRecd: 69300,
      BILLS_GSTRecdDate: '2026-06-04',
      BILLS_Mode: 'NEFT',
      BILLS_Ref: 'NEFT2606001',
      BILLS_GSTR1Check: true,
      BILLS_GSTR1FiledOn: '2026-06-11',
      BILLS_GSTR1Ref: 'GSTR1-JUN26-001',
      BILLS_GSTR1Issue: '',
      BILLS_GSTR1Resolution: '',
      BILLS_GSTR3BPaid: 69300,
      BILLS_GSTR3BPaidOn: '2026-06-20',
      BILLS_GSTR3BRef: 'GSTR3B-JUN26-001',
      BILLS_GSTTDSRecd: 0,
      BILLS_TDSCreditFiledOn: '',
      BILLS_TDSClaimRef: '',
      BILLS_Comments: '',
    },
    {
      BILLS_BillNum: 2,
      BILLS_ClientCode: 'TEN-002',
      BILLS_BillDate: '2026-06-01',
      BILLS_BillGenDate: '2026-06-01T09:14:00',
      BILLS_Description: 'Rent for June 2026',
      BILLS_Total: 165000,
      BILLS_RentRecd: 0,
      BILLS_RentRecdDate: '',
      BILLS_TDSDep: 0,
      BILLS_TDSDepDate: '',
      BILLS_GSTRecd: 0,
      BILLS_GSTRecdDate: '',
      BILLS_Mode: '',
      BILLS_Ref: '',
      BILLS_GSTR1Check: false,
      BILLS_GSTR1FiledOn: '',
      BILLS_GSTR1Ref: '',
      BILLS_GSTR1Issue: 'Pending payment',
      BILLS_GSTR1Resolution: '',
      BILLS_GSTR3BPaid: 0,
      BILLS_GSTR3BPaidOn: '',
      BILLS_GSTR3BRef: '',
      BILLS_GSTTDSRecd: 0,
      BILLS_TDSCreditFiledOn: '',
      BILLS_TDSClaimRef: '',
      BILLS_Comments: 'Follow up with tenant.',
    },
    {
      BILLS_BillNum: 3,
      BILLS_ClientCode: 'TEN-003',
      BILLS_BillDate: '2026-06-01',
      BILLS_BillGenDate: '2026-06-01T09:20:00',
      BILLS_Description: 'Rent for June 2026',
      BILLS_Total: 275000,
      BILLS_RentRecd: 275000,
      BILLS_RentRecdDate: '2026-06-02',
      BILLS_TDSDep: 27500,
      BILLS_TDSDepDate: '2026-06-06',
      BILLS_GSTRecd: 0,
      BILLS_GSTRecdDate: '',
      BILLS_Mode: 'RTGS',
      BILLS_Ref: 'RTGS2606044',
      BILLS_GSTR1Check: false,
      BILLS_GSTR1FiledOn: '',
      BILLS_GSTR1Ref: '',
      BILLS_GSTR1Issue: '',
      BILLS_GSTR1Resolution: '',
      BILLS_GSTR3BPaid: 0,
      BILLS_GSTR3BPaidOn: '',
      BILLS_GSTR3BRef: '',
      BILLS_GSTTDSRecd: 0,
      BILLS_TDSCreditFiledOn: '',
      BILLS_TDSClaimRef: '',
      BILLS_Comments: 'Non-GST invoice.',
    },
  ],
};
